name: "Docker"

on:
  push:
    branches: ["master"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  build:
    name: "Build"
    uses: marekp/dockette-web/.github/workflows/build.yml@master
    secrets: inherit
    with:
      image: "pinkava/web"
      tag: "${{ matrix.tag }}"
      context: "${{ matrix.context }}"
    strategy:
      matrix:
        include:
          - { context: debian-php-83, tag: php-83 }
